apiVersion: apps/v1
kind: Deployment

metadata:
  name: "{{ .Values.metadata.name2 }}"
spec:
  replicas: "{{ .Values.replicaCount }}"
  selector:
    matchLabels:
      component: "{{ .Values.image2.repository }}"


  template:
    metadata:
      labels: 
        component: "{{ .Values.image2.repository }}"
  
    spec:
      volumes:
      - name: "{{ .Values.volume.name }}"
        persistentVolumeClaim:
          claimName: "{{ .Values.volume.claimName }}"

      containers:
      - name: "{{ .Values.image2.repository }}"
        image: "{{ .Values.image2.repository }}:{{ .Values.image2.tag| default .Chart.AppVersion }}"
        ports: 
        - containerPort: "{{ .Values.service.port }}"

        volumeMounts:
        - name: "{{ .Values.volume.name }}"   
          mountPath: /var/lib/postgresql/data
          subPath: postgres
            
        env:
           - name: POSTGRES_USER
             value: "{{ .Values.env.postgres.namevalue }}"
           - name: POSTGRES_DB
             value: "{{ .Values.env.postgres.dbvalue }}"
           - name: POSTGRES_PASSWORD
             valueFrom: 
               secretKeyRef:
                 name: "{{ .Values.env.postgres.secret.name }}"
                 key: "{{ .Values.env.postgres.secret.key }}"