apiVersion: v1
kind: Service

metadata:
  name: "{{ .Values.service.name2 }}"

spec:
  selector:
    component: "{{ .Values.image2.repository }}"
  
  type: "{{ .Values.service.type }}"

  ports: 
    - port: 5432
      targetPort: 5432