apiVersion: v1

kind: Service

metadata:
  name: "{{ .Values.service.name1 }}"

spec:
  selector:
    component: "{{ .Values.image.repository }}"

  type: "{{ .Values.service.type }}"
  ports: 
    - port: 6379
      targetPort: 6379