apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.service.name3 }}"

spec:
  selector:
    component: "{{ .Values.image3.name }}"
  type: "{{ .Values.service.type }}"
  ports:
    - port: "{{ .Values.service.port3 }}"
      targetPort: "{{ .Values.service.port3 }}"